/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file ".s21_test.kek" instead.
 */

#include <check.h>
#include <string.h>

#include "../s21_string.h"
#define NMAX 1024
#define AMOUNT 10
#define BUFF_SIZE 1024

START_TEST(strlen_test) {
  char str1[30] = "day\n";
  char str2[30] = "An awf\tul day";
  char str3[30] = "Wiggam's aw\0ful day";
  char str4[30] = "3 4 ";
  char str5[30] = "1 2 3 4 5 ";
  char str6[30] = "";

  ck_assert_int_eq(s21_strlen(str1), strlen(str1));
  ck_assert_int_eq(s21_strlen(str2), strlen(str2));
  ck_assert_int_eq(s21_strlen(str3), strlen(str3));
  ck_assert_int_eq(s21_strlen(str4), strlen(str4));
  ck_assert_int_eq(s21_strlen(str5), strlen(str5));
  ck_assert_int_eq(s21_strlen(str6), strlen(str6));
}
END_TEST

START_TEST(strcspn_test) {
  char str1[30] = "day";
  char str2[30] = "An awful day";
  char str3[30] = "Wiggam's awful day";
  char str4[30] = "3 4 ";
  char str5[30] = "1 2 3 4 5 ";
  char str6[30] = "";

  ck_assert_int_eq(s21_strcspn(str2, str1), strcspn(str2, str1));
  ck_assert_int_eq(s21_strcspn(str3, str1), strcspn(str3, str1));
  ck_assert_int_eq(s21_strcspn(str5, str4), strcspn(str5, str4));
  ck_assert_int_eq(s21_strcspn(str5, str6), strcspn(str5, str6));
  ck_assert_int_eq(s21_strcspn(str6, str1), strcspn(str6, str1));
}
END_TEST

START_TEST(strerror_test) {
  char *str1 = s21_strerror(21);
  char *str2 = strerror(21);
  ck_assert_str_eq(str1, str2);

  char *str3 = s21_strerror(14);
  char *str4 = strerror(14);
  ck_assert_str_eq(str3, str4);

  char *str5 = s21_strerror(1001);
  char *str6 = strerror(1001);
  ck_assert_str_eq(str5, str6);

  char *str7 = s21_strerror(1);
  char *str8 = strerror(1);
  ck_assert_str_eq(str7, str8);

  char *str9 = s21_strerror(27);
  char *str10 = strerror(27);
  ck_assert_str_eq(str9, str10);
  char *str11 = s21_strerror(-1);
  char *str12 = strerror(-1);
  ck_assert_str_eq(str11, str12);
}
END_TEST

START_TEST(strtok_test) {
  char test1[50] = "hehehe,hello,world,s21_school";
  char test2[50] = "hehehe,hello,world,s21_school";
  char delim1[10] = "2,1";
  char *orig1 = {0}, *copy1 = {0};
  orig1 = strtok(test1, delim1);
  copy1 = s21_strtok(test2, delim1);
  char orig_res1[1000] = {0};
  char copy_res1[1000] = {0};
  while (orig1 != NULL) {
    strcat(orig_res1, orig1);
    orig1 = strtok(NULL, delim1);
  }
  while (copy1 != NULL) {
    strcat(copy_res1, copy1);
    copy1 = s21_strtok(s21_NULL, delim1);
  }
  ck_assert_str_eq(orig_res1, copy_res1);

  char str[] = "School-69";
  char *s21tok1 = s21_strtok(str, "-");
  char *s21tok2 = strtok(str, "-");
  char *s21tok3 = s21_strtok(str, "");
  char *s21tok4 = strtok(str, "");
  char *s21tok5 = s21_strtok(str, "oo");
  char *s21tok6 = strtok(str, "oo");
  char *s21tok7 = s21_strtok(str, "Sc");
  char *s21tok8 = strtok(str, "Sc");
  char *s21tok9 = s21_strtok(str, "69");
  char *s21tok10 = strtok(str, "69");
  ck_assert_msg(!strcmp(s21tok1, s21tok2), "1st strtok test failed");
  ck_assert_msg(!strcmp(s21tok3, s21tok4), "2nd strtok test failed");
  ck_assert_msg(!strcmp(s21tok5, s21tok6), "3rd strtok test failed");
  ck_assert_msg(!strcmp(s21tok7, s21tok8), "4rth strtok test failed");
  ck_assert_msg(!strcmp(s21tok9, s21tok10), "5th strtok test failed");
}
END_TEST

START_TEST(strncpy_test) {
  char str1[30] = "";
  char str2[30] = " ";
  char str3[30] = "One ice-cream";
  char str4[30] = "One\nice-cream";
  char str5[30] = "One\0ice-cream";
  char str6[30] = "One\tice-cream";
  char str7[30] = "Love";
  ck_assert_pstr_eq(strncpy(str1, str3, 15), s21_strncpy(str1, str3, 15));
  ck_assert_pstr_eq(strncpy(str2, str3, 14), s21_strncpy(str2, str3, 14));
  ck_assert_pstr_eq(strncpy(str3, str7, 4), s21_strncpy(str3, str7, 4));
  ck_assert_pstr_eq(strncpy(str3, str4, 7), s21_strncpy(str3, str4, 7));
  ck_assert_pstr_eq(strncpy(str4, str7, 4), s21_strncpy(str4, str7, 4));
  ck_assert_pstr_eq(strncpy(str5, str7, 4), s21_strncpy(str5, str7, 4));
  ck_assert_pstr_eq(strncpy(str5, str3, 9), s21_strncpy(str5, str3, 9));
  ck_assert_pstr_eq(strncpy(str6, str7, 4), s21_strncpy(str6, str7, 4));
  ck_assert_pstr_eq(strncpy(str7, str2, 4), s21_strncpy(str7, str2, 4));
}
END_TEST

START_TEST(memcpy_test) {
  char str1[30] = "";
  char str2[30] = " ";
  char str3[30] = "One ice-cream";
  char str4[30] = "One\nice-cream";
  char str5[30] = "One\0ice-cream";
  char str6[30] = "One\tice-cream";
  char str7[30] = "Love";
  ck_assert_pstr_eq(memcpy(str1, str3, 5), s21_memcpy(str1, str3, 5));
  ck_assert_pstr_eq(memcpy(str2, str3, 5), s21_memcpy(str2, str3, 5));
  ck_assert_pstr_eq(memcpy(str3, str7, 4), s21_memcpy(str3, str7, 4));
  ck_assert_pstr_eq(memcpy(str3, str4, 7), s21_memcpy(str3, str4, 7));
  ck_assert_pstr_eq(memcpy(str3, str4, 0), s21_memcpy(str3, str4, 0));
  ck_assert_pstr_eq(memcpy(str4, str7, 4), s21_memcpy(str4, str7, 4));
  ck_assert_pstr_eq(memcpy(str5, str7, 4), s21_memcpy(str5, str7, 4));
  ck_assert_pstr_eq(memcpy(str5, str3, 9), s21_memcpy(str5, str3, 9));
  ck_assert_pstr_eq(memcpy(str6, str7, 4), s21_memcpy(str6, str7, 4));
  ck_assert_pstr_eq(memcpy(str7, str2, 4), s21_memcpy(str7, str2, 4));
}
END_TEST

START_TEST(memset_test) {
  char str1[30] = "";
  char str2[30] = " ";
  char str3[30] = "One ice-cream";
  char str4[30] = "One\nice-cream";
  char str5[30] = "One\0ice-cream";
  char str6[30] = "One\tice-cream";
  ck_assert_pstr_eq(memset(str1, '5', 1), s21_memset(str1, '5', 1));
  ck_assert_pstr_eq(memset(str2, '5', 1), s21_memset(str2, '5', 1));
  ck_assert_pstr_eq(memset(str3, '1', 3), s21_memset(str3, '1', 3));
  ck_assert_pstr_eq(memset(str3, '7', 7), s21_memset(str3, '7', 7));
  ck_assert_pstr_eq(memset(str3, '\t', 3), s21_memset(str3, '\t', 3));
  ck_assert_pstr_eq(memset(str3, 'U', 3), s21_memset(str3, 'U', 3));
  ck_assert_pstr_eq(memset(str3, '^', 7), s21_memset(str3, '^', 7));
  ck_assert_pstr_eq(memset(str4, '7', 7), s21_memset(str4, '7', 7));
  ck_assert_pstr_eq(memset(str4, '\t', 1), s21_memset(str4, '\t', 1));
  ck_assert_pstr_eq(memset(str4, 'U', 7), s21_memset(str4, 'U', 7));
  ck_assert_pstr_eq(memset(str4, '^', 7), s21_memset(str4, '^', 7));
  ck_assert_pstr_eq(memset(str5, '7', 7), s21_memset(str5, '7', 7));
  ck_assert_pstr_eq(memset(str5, '\t', 1), s21_memset(str5, '\t', 1));
  ck_assert_pstr_eq(memset(str5, 'U', 7), s21_memset(str5, 'U', 7));
  ck_assert_pstr_eq(memset(str5, '^', 7), s21_memset(str5, '^', 7));
  ck_assert_pstr_eq(memset(str6, '7', 7), s21_memset(str5, '7', 7));
  ck_assert_pstr_eq(memset(str6, '\t', 1), s21_memset(str6, '\t', 1));
  ck_assert_pstr_eq(memset(str6, 'U', 7), s21_memset(str6, 'U', 7));
  ck_assert_pstr_eq(memset(str6, '^', 7), s21_memset(str6, '^', 7));
}
END_TEST

START_TEST(strstr_test) {
  char *str1 = "";
  char *str2 = " ";
  char *str3 = "One ice-cream";
  char *str4 = "One\nice-cream";
  char *str5 = "One\0ice-cream";
  char *str6 = "One\tice-cream";
  char *str7 = "Love";
  char *str8 = "\0";
  char *str9 = "strawberry";
  ck_assert_pstr_eq(strstr(str1, str3), s21_strstr(str1, str3));
  ck_assert_pstr_eq(strstr(str2, str3), s21_strstr(str2, str3));
  ck_assert_pstr_eq(strstr(str3, str7), s21_strstr(str3, str7));
  ck_assert_pstr_eq(strstr(str3, str1), s21_strstr(str3, str1));
  ck_assert_pstr_eq(strstr(str3, str2), s21_strstr(str3, str2));
  ck_assert_pstr_eq(strstr(str3, str4), s21_strstr(str3, str4));
  ck_assert_pstr_eq(strstr(str3, str9), s21_strstr(str3, str9));
  ck_assert_pstr_eq(strstr(str7, str9), s21_strstr(str7, str9));
  ck_assert_pstr_eq(strstr(str3, str4), s21_strstr(str3, str4));
  ck_assert_pstr_eq(strstr(str4, str7), s21_strstr(str4, str7));
  ck_assert_pstr_eq(strstr(str5, str7), s21_strstr(str5, str7));
  ck_assert_pstr_eq(strstr(str5, str3), s21_strstr(str5, str3));
  ck_assert_pstr_eq(strstr(str6, str7), s21_strstr(str6, str7));
  ck_assert_pstr_eq(strstr(str7, str2), s21_strstr(str7, str2));
  ck_assert_pstr_eq(strstr(str8, str3), s21_strstr(str8, str3));
  ck_assert_pstr_eq(strstr(str7, str8), s21_strstr(str7, str8));
}
END_TEST

START_TEST(strchr_test) {
  char *str1 = "ice-cream clean line";
  char *str2 = "ice-cream\tclean line";
  char *str3 = "ice-cream\nclean line";
  char *str4 = "ice-cream\0clean line";
  char *str5 = "";
  char *str6 = "\0";
  char *str7 = " ";
  ck_assert_pstr_eq(strchr(str1, 'c'), s21_strchr(str1, 'c'));
  ck_assert_pstr_eq(strchr(str1, 'f'), s21_strchr(str1, 'f'));
  ck_assert_pstr_eq(strchr(str1, ' '), s21_strchr(str1, ' '));
  ck_assert_pstr_eq(strchr(str1, 'a'), s21_strchr(str1, 'a'));
  ck_assert_pstr_eq(strchr(str2, '\t'), s21_strchr(str2, '\t'));
  ck_assert_pstr_eq(strchr(str3, '\n'), s21_strchr(str3, '\n'));
  ck_assert_pstr_eq(strchr(str1, 'e'), s21_strchr(str1, 'e'));
  ck_assert_pstr_eq(strchr(str4, '\0'), s21_strchr(str4, '\0'));
  ck_assert_pstr_eq(strchr(str5, 'c'), s21_strchr(str5, 'c'));
  ck_assert_pstr_eq(strchr(str6, 'c'), s21_strchr(str6, 'c'));
  ck_assert_pstr_eq(strchr(str7, 'c'), s21_strchr(str7, 'c'));
}
END_TEST

START_TEST(strrchr_test) {
  char *str1 = "ice-cream clean line";
  char *str2 = "ice-cream\tclean line";
  char *str3 = "ice-cream\nclean line";
  char *str4 = "ice-cream\0clean line";
  char *str5 = "";
  char *str6 = "\0";
  char *str7 = " ";
  ck_assert_pstr_eq(strrchr(str1, 'c'), s21_strrchr(str1, 'c'));
  ck_assert_pstr_eq(strrchr(str1, 'f'), s21_strrchr(str1, 'f'));
  ck_assert_pstr_eq(strrchr(str1, ' '), s21_strrchr(str1, ' '));
  ck_assert_pstr_eq(strrchr(str1, 'a'), s21_strrchr(str1, 'a'));
  ck_assert_pstr_eq(strrchr(str2, '\t'), s21_strrchr(str2, '\t'));
  ck_assert_pstr_eq(strrchr(str3, '\n'), s21_strrchr(str3, '\n'));
  ck_assert_pstr_eq(strrchr(str4, '\0'), s21_strrchr(str4, '\0'));
  ck_assert_pstr_eq(strrchr(str5, 'c'), s21_strrchr(str5, 'c'));
  ck_assert_pstr_eq(strrchr(str6, 'c'), s21_strrchr(str6, 'c'));
  ck_assert_pstr_eq(strrchr(str7, 'c'), s21_strrchr(str7, 'c'));
}
END_TEST

START_TEST(memchr_test) {
  char str1[69] = "ice-cream clean line";
  char str2[69] = "ice-cream\0clean line";
  char str3[69] = "";
  char str4[69] = "\0";
  char str5[69] = "ice-cream\tclean line";
  char str6[69] = " ";
  ck_assert_pstr_eq(memchr(str1, 'c', 0), s21_memchr(str1, 'c', 0));
  ck_assert_pstr_eq(memchr(str1, 'c', 3), s21_memchr(str1, 'c', 3));
  ck_assert_pstr_eq(memchr(str1, 'c', 16), s21_memchr(str1, 'c', 16));
  ck_assert_pstr_eq(memchr(str1, 'f', 30), s21_memchr(str1, 'f', 30));
  ck_assert_pstr_eq(memchr(str1, 'f', 5), s21_memchr(str1, 'f', 5));
  ck_assert_pstr_eq(memchr(str1, 'a', 0), s21_memchr(str1, 'a', 0));
  ck_assert_pstr_eq(memchr(str2, '\0', 21), s21_memchr(str2, '\0', 21));
  ck_assert_pstr_eq(memchr(str3, 'c', 3), s21_memchr(str3, 'c', 3));
  ck_assert_pstr_eq(memchr(str4, 'c', 3), s21_memchr(str4, 'c', 3));
  ck_assert_pstr_eq(memchr(str5, '\t', 21), s21_memchr(str5, '\t', 21));
  ck_assert_pstr_eq(memchr(str6, 'a', 21), s21_memchr(str6, 'a', 21));
  ck_assert_pstr_eq(memchr(str1, ' ', 21), s21_memchr(str1, ' ', 21));
}
END_TEST

START_TEST(strpbrk_test) {
  char *str1 = "ice-cream";
  char *str2 = "ice";
  char *str3 = "ab";
  char *str4 = "s";
  char *str5 = "jbhfdighp";
  char *str6 = "bhf";
  char *str7 = "ice-cream clean line";
  char *str8 = "cream";
  char *str9 = "ice-cream\0clean line";
  char *str10 = "cream";
  char *str11 = "";
  char *str12 = " ";
  ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));
  ck_assert_pstr_eq(strpbrk(str1, str3), s21_strpbrk(str1, str3));
  ck_assert_pstr_eq(strpbrk(str1, str4), s21_strpbrk(str1, str4));
  ck_assert_pstr_eq(strpbrk(str1, str6), s21_strpbrk(str1, str6));
  ck_assert_pstr_eq(strpbrk(str5, str6), s21_strpbrk(str5, str6));
  ck_assert_pstr_eq(strpbrk(str7, str8), s21_strpbrk(str7, str8));
  ck_assert_pstr_eq(strpbrk(str9, str10), s21_strpbrk(str9, str10));
  ck_assert_pstr_eq(strpbrk(str11, str10), s21_strpbrk(str11, str10));
  ck_assert_pstr_eq(strpbrk(str10, str11), s21_strpbrk(str10, str11));
  ck_assert_pstr_eq(strpbrk(str7, str12), s21_strpbrk(str7, str12));
  ck_assert_pstr_eq(strpbrk(str12, str7), s21_strpbrk(str12, str7));
}
END_TEST

START_TEST(memcmp_test) {
  int result = 0;

  const char *str1 = "hello";
  const char *str2 = "hello";
  result = s21_memcmp(str1, str2, strlen(str1));  // убрать strlen
  ck_assert_int_eq(result, memcmp(str1, str2, strlen(str1)));

  const char *str3 = "School";
  const char *str4 = "School 21";
  result = s21_memcmp(str3, str4, strlen(str3));  // убрать strlen
  ck_assert_int_eq(result, memcmp(str3, str4, strlen(str3)));

  const char *str5 = "hello";
  const char *str6 = "goodbye";
  result = s21_memcmp(str5, str6, strlen(str5));  // убрать strlen
  ck_assert_int_eq(result, memcmp(str5, str6, strlen(str5)));
}
END_TEST

START_TEST(strncmp_test) {
  int result = 0;
  const char *str1 = "hello";
  const char *str2 = "hello";
  result = s21_strncmp(str1, str2, strlen(str1));  // убрать strlen
  ck_assert_int_eq(result, strncmp(str1, str2, strlen(str1)));

  const char *str3 = "School";
  const char *str4 = "School 21";
  result = s21_strncmp(str3, str4, strlen(str3));  // убрать strlen
  ck_assert_int_eq(result, strncmp(str3, str4, strlen(str3)));

  const char *str5 = "hello";
  const char *str6 = "goodbye";
  result = s21_strncmp(str5, str6, strlen(str5));  // убрать strlen
  ck_assert_int_eq(result, strncmp(str5, str6, strlen(str5)));
}
END_TEST

START_TEST(test_default) {
  char result[20] = {0};
  char assert[20] = {0};
  s21_sprintf(result, "Count: %c", 'a');
  sprintf(assert, "Count: %c", 'a');
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default2) {
  char result[20] = {0};
  char assert[20] = {0};
  char c = 'b';
  s21_sprintf(result, "Count: %c", c);
  sprintf(assert, "Count: %c", c);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default3) {
  char result[20] = {0};
  char assert[20] = {0};
  char c = 'b';
  int a = s21_sprintf(result, "Count: %5c", c);
  int b = sprintf(assert, "Count: %5c", c);
  ck_assert_str_eq(result, assert);
  ck_assert_int_eq(a, b);
}
END_TEST

START_TEST(test_default4) {
  char result[20] = {0};
  char assert[20] = {0};
  char c = 'b';
  int a = s21_sprintf(result, "Count: %-5c", c);
  int b = sprintf(assert, "Count: %-5c", c);
  ck_assert_str_eq(result, assert);
  ck_assert_int_eq(a, b);
}
END_TEST

START_TEST(test_default5) {
  char result[1120] = {'\0'};
  char assert[1120] = {'\0'};
  char c = 'z';
  s21_sprintf(result, "Count: %lc", c);
  sprintf(assert, "Count: %lc", c);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default6) {
  char result[20] = {0};
  char assert[20] = {0};
  char c = 'a';
  s21_sprintf(result, "Count: %-3c", c);
  sprintf(assert, "Count: %-3c", c);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default7) {  // need to fix '*'
  char result[20] = {0};
  char assert[20] = {0};
  char c = 'a';
  s21_sprintf(result, "Count: %*c", 4, c);
  sprintf(assert, "Count: %*c", 4, c);
  ck_assert_str_eq(result, assert);
}
END_TEST

// START_TEST(test_default8) {
//   char result[1120] = {0};
//   char assert[1120] = {0};
//   long long d = 5717984;
//   s21_sprintf(result, "Count: %Li 1", d);
//   sprintf(assert, "Count: %Li 1", d);
//   ck_assert_str_eq(result, assert);
// }
// END_TEST

START_TEST(test_default10) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 57;
  s21_sprintf(result, "Count: %d abc", d);
  sprintf(assert, "Count: %d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default9) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 190;
  s21_sprintf(result, "Count: %5d", d);
  sprintf(assert, "Count: %5d", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default_multy) {
  char result[20] = {0};
  char assert[20] = {0};
  s21_sprintf(result, "Count: %d%d%d%d", -4, 8, 15, 16);
  sprintf(assert, "Count: %d%d%d%d", -4, 8, 15, 16);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default11) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 571212;
  s21_sprintf(result, "Count: %.5d abc", d);
  sprintf(assert, "Count: %.5d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default12) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 5312112;
  s21_sprintf(result, "Count: %-.5d abc", d);
  sprintf(assert, "Count: %-.5d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default13) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 0;
  s21_sprintf(result, "Count: %d abc", d);
  sprintf(assert, "Count: %d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default14) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 0;
  s21_sprintf(result, "Count: %d abc", d);
  sprintf(assert, "Count: %d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default15) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = 1;
  s21_sprintf(result, "Count: % d abc", d);
  sprintf(assert, "Count: % d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default16) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = -1;
  s21_sprintf(result, "Count: % d abc", d);
  sprintf(assert, "Count: % d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default17) {
  char result[20] = {0};
  char assert[20] = {0};
  int d = -0;
  s21_sprintf(result, "Count: % d abc", d);
  sprintf(assert, "Count: % d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default18) {
  char result[40] = {0};
  char assert[40] = {0};
  int d = 2147483647;
  s21_sprintf(result, "Count: % d abc", d);
  sprintf(assert, "Count: % d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default19) {
  char result[40] = {0};
  char assert[40] = {0};
  int d = -2147483648;
  s21_sprintf(result, "Count: % d abc", d);
  sprintf(assert, "Count: % d abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default20) {
  char result[40] = {0};
  char assert[40] = {0};
  long int d = 2147483647;
  s21_sprintf(result, "Count: % ld abc", d);
  sprintf(assert, "Count: % ld abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default21) {
  char result[40] = {0};
  char assert[40] = {0};
  long int d = -2147483648;
  s21_sprintf(result, "Count: % ld abc", d);
  sprintf(assert, "Count: % ld abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default22) {
  char result[40] = {0};
  char assert[40] = {0};
  long int d = 3232323;
  s21_sprintf(result, "Count: %ld abc", d);
  sprintf(assert, "Count: %ld abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default23) {
  char result[40] = {0};
  char assert[40] = {0};
  short int d = 32767;
  s21_sprintf(result, "Count: %hd abc", d);
  sprintf(assert, "Count: %hd abc", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default24) {
  char result[40] = {0};
  char assert[40] = {0};
  short int d = 32767;
  s21_sprintf(result, "Count: %hd end", d);
  sprintf(assert, "Count: %hd end", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default25) {
  char result[40] = {0};
  char assert[40] = {0};
  int d = 327710;
  s21_sprintf(result, "Count: %11.10d end", d);
  sprintf(assert, "Count: %11.10d end", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default26) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 57;
  s21_sprintf(result, "Count: %i 1", i);
  sprintf(assert, "Count: %i 1", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default27) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 57;
  s21_sprintf(result, "Count: %i abc", i);
  sprintf(assert, "Count: %i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default28) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 190;
  s21_sprintf(result, "Count: %5i", i);
  sprintf(assert, "Count: %5i", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default29) {
  char result[20] = {0};
  char assert[20] = {0};
  s21_sprintf(result, "Count: %i%i%i%i", -4, 8, 15, 16);
  sprintf(assert, "Count: %i%i%i%i", -4, 8, 15, 16);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default30) {
  char result[20] = {0};
  char assert[20] = {0};
  s21_sprintf(result, "Count: %1.1i", 69);
  sprintf(assert, "Count: %1.1i", 69);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default31) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 571212;
  s21_sprintf(result, "Count: %.5i abc", i);
  sprintf(assert, "Count: %.5i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default32) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 5312112;
  s21_sprintf(result, "Count: %-.5i abc", i);
  sprintf(assert, "Count: %-.5i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default33) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 0;
  s21_sprintf(result, "Count: %i abc", i);
  sprintf(assert, "Count: %i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default34) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 0;
  s21_sprintf(result, "Count: %i abc", i);
  sprintf(assert, "Count: %i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default35) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = 1;
  s21_sprintf(result, "Count: % i abc", i);
  sprintf(assert, "Count: % i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default36) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = -1;
  s21_sprintf(result, "Count: % i abc", i);
  sprintf(assert, "Count: % i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default37) {
  char result[20] = {0};
  char assert[20] = {0};
  int i = -0;
  s21_sprintf(result, "Count: % i abc", i);
  sprintf(assert, "Count: % i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default38) {
  char result[40] = {0};
  char assert[40] = {0};
  int i = 2147483647;
  s21_sprintf(result, "Count: % i abc", i);
  sprintf(assert, "Count: % i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default39) {
  char result[40] = {0};
  char assert[40] = {0};
  int i = -2147483648;
  s21_sprintf(result, "Count: % i abc", i);
  sprintf(assert, "Count: % i abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default40) {
  char result[40] = {0};
  char assert[40] = {0};
  long int i = 2147483648;
  s21_sprintf(result, "Count: % li abc", i);
  sprintf(assert, "Count: % li abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default43) {
  char result[40] = {0};
  char assert[40] = {0};
  short int i = 32767;
  s21_sprintf(result, "Count: %hi abc", i);
  sprintf(assert, "Count: %hi abc", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default44) {
  char result[40] = {0};
  char assert[40] = {0};
  short int i = 32767;
  s21_sprintf(result, "Count: %hi end", i);
  sprintf(assert, "Count: %hi end", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default45) {
  char result[40] = {0};
  char assert[40] = {0};
  int i = 327710;
  s21_sprintf(result, "Count: %5.10i end", i);
  sprintf(assert, "Count: %5.10i end", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default46) {
  char result[40] = {0};
  char assert[40] = {0};
  int i = 327710;
  s21_sprintf(result, "Count: %-+10.5i end", i);
  sprintf(assert, "Count: %-+10.5i end", i);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default47) {
  char result[40] = {0};
  char assert[40] = {0};
  int i = 327710;
  s21_sprintf(result, "Count: %+10.5i end", i + 1);
  sprintf(assert, "Count: %+10.5i end", i + 1);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default48) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = -14.537;
  s21_sprintf(result, "Count: %.6f end", f);
  sprintf(assert, "Count: %.6f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default49) {
  char result[140] = {0};
  char assert[140] = {0};
  float f = 14.537;
  s21_sprintf(result, "Count: %2.2f end", f);
  sprintf(assert, "Count: %2.2f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default50) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = 1.0010021;
  s21_sprintf(result, "Count: %f end", f);
  sprintf(assert, "Count: %f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default51) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = 0;
  s21_sprintf(result, "Count: %f end", f);
  sprintf(assert, "Count: %f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default52) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = 0.;
  s21_sprintf(result, "Count: %f end", f);
  sprintf(assert, "Count: %f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default53) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = -123.321;
  s21_sprintf(result, "Count: %f end", f);
  sprintf(assert, "Count: %f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default54) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = 1.1234;
  s21_sprintf(result, "Count: %.*f end", 3, f);
  sprintf(assert, "Count: %.*f end", 3, f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default55) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = -.0000001;
  s21_sprintf(result, "Count: %f end", f);
  sprintf(assert, "Count: %f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default56) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = -.0000001;
  s21_sprintf(result, "Count: %10f end", f);
  sprintf(assert, "Count: %10f end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default57) {
  char result[40] = {0};
  char assert[40] = {0};
  double f = -.0000001;
  s21_sprintf(result, "Count: %3.5lf end", f);
  sprintf(assert, "Count: %3.5lf end", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(float_precision) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%Lf";
  long double val = 513515.131513515151351;
  int a = s21_sprintf(str1, format, val);
  int b = sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(a, b);
}
END_TEST
START_TEST(float_width) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%10Lf";
  long double val = 15.35;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(float_precision_zero) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.0Lf";
  long double val = 15.35;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(float_precision_empty) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.Lf";
  long double val = 15.35;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(float_precision_huge) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.15Lf";
  long double val = 15.35;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(float_precision_huge_negative) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.15Lf";
  long double val = -15.35581134;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(float_huge) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%Lf";
  long double val = 72537572375.1431341;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(float_flags) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "% f";
  float val = 0;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(float_many) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "% .0f %.lf %Lf %f %lf %Lf";
  float val = 0;
  double val1 = 0;
  long double val2 = 3515315.153151;
  float val3 = 5.5;
  double val4 = 9851.51351;
  long double val5 = 95919539159.53151351131;
  s21_sprintf(str1, format, val, val1, val2, val3, val4, val5);
  sprintf(str2, format, val, val1, val2, val3, val4, val5);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_one_float) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  ck_assert_int_eq(s21_sprintf(str1, "%f", 0.0001),
                   sprintf(str2, "%f", 0.0001));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_many_float) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  ck_assert_int_eq(
      s21_sprintf(str1, "%f%f%f%f", -999.666, 0.0001, 666.999, -100.001),
      sprintf(str2, "%f%f%f%f", -999.666, 0.0001, 666.999, -100.001));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default58) {
  char result[40] = {0};
  char assert[40] = {0};
  float f = 14.537;
  s21_sprintf(result, "%+0.2f", f);
  sprintf(assert, "%+0.2f", f);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default59) {
  char result[40] = {0};
  char assert[40] = {0};
  char *s = "none";
  s21_sprintf(result, "Count: %s abc", s);
  sprintf(assert, "Count: %s abc", s);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default60) {
  char result[40] = {0};
  char assert[40] = {0};
  char *s = "none";
  s21_sprintf(result, "Count: %.3s abc", s);
  sprintf(assert, "Count: %.3s abc", s);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default61) {
  char result[40] = {0};
  char assert[40] = {0};
  char *s = "none";
  s21_sprintf(result, "%.6s", s);
  sprintf(assert, "%.6s", s);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default62) {
  char result[40] = {0};
  char assert[40] = {0};
  char *s = "stroka s probelom";
  s21_sprintf(result, "%5.6s", s);
  sprintf(assert, "%5.6s", s);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default63) {
  char result[40] = {0};
  char assert[40] = {0};
  char *s = "stroka s probelom";
  s21_sprintf(result, "%-5.6s", s);
  sprintf(assert, "%-5.6s", s);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(string) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%s";
  char *val = "21R DSADA SDHASDOAMDSA sdas8d7nasd 111";
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(string_precision) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%.15s";
  char *val = "21R DSADA SDHASDOAMDSA sdas8d7nasd 111";
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(string_width) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%15s";
  char *val = "21R DSADA SDHASDOAMDSA sdas8d7nasd 111";
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(string_flags) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%-15.9s";
  char *val = "21R DSADA SDHASDOAMDSA sdas8d7nasd 111";
  s21_sprintf(str1, format, val), sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(string_long) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%s";
  char *val = "ADibsy8 ndASN) dun8AWn dA 9sDNsa NAID saDYBU DSnaJ Sd";
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(string_many) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%s%s%s%s";
  char *val = "ADibsy8 ndASN) dun8AWn dA 9sDNsa NAID saDYBU DSnaJ Sd";
  char *s1 = "";
  char *s2 = "87418347813748913749871389480913";
  char *s3 = "HAHAABOBASUCKER";
  ck_assert_int_eq(s21_sprintf(str1, format, val, s1, s2, s3),
                   sprintf(str2, format, val, s1, s2, s3));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(string_width_huge) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *val = "kjafdiuhfjahfjdahf";
  char *format = "%120s";
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_one_string) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  ck_assert_int_eq(s21_sprintf(str1, "%s", "DASdw D sadw ASD"),
                   sprintf(str2, "%s", "DASdw D sadw ASD"));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_many_string) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  ck_assert_int_eq(
      s21_sprintf(str1, "%s%s%s%s%s", "DASdw", " ", "sadw", " ", "ASD"),
      sprintf(str2, "%s%s%s%s%s", "DASdw", " ", "sadw", " ", "ASD"));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default65) {
  char result[20] = {0};
  char assert[20] = {0};
  unsigned int u = 571212;
  s21_sprintf(result, "Count: %.5u abc", u);
  sprintf(assert, "Count: %.5u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default66) {
  char result[20] = {0};
  char assert[20] = {0};
  unsigned int u = 5312112;
  s21_sprintf(result, "Count: %-.5u abc", u);
  sprintf(assert, "Count: %-.5u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default67) {
  char result[20] = {0};
  char assert[20] = {0};
  unsigned int u = 0;
  s21_sprintf(result, "Count: %u abc", u);
  sprintf(assert, "Count: %u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default68) {
  char result[20] = {0};
  char assert[20] = {0};
  unsigned int u = 0;
  s21_sprintf(result, "Count: %u abc", u);
  sprintf(assert, "Count: %u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default69) {
  char result[1220] = {0};
  char assert[1220] = {0};
  long unsigned int u = 91919929929299292;
  s21_sprintf(result, "Count: %lu abc", u);
  sprintf(assert, "Count: %lu abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default70) {
  char result[20] = {0};
  char assert[20] = {0};
  unsigned int u = 1;
  s21_sprintf(result, "Count: %u abc", u);
  sprintf(assert, "Count: %u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default71) {
  char result[20] = {0};
  char assert[20] = {0};
  unsigned int u = -0;
  s21_sprintf(result, "Count: %u abc", u);
  sprintf(assert, "Count: %u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default72) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned int u = 2147483647;
  s21_sprintf(result, "Count: %u abc", u);
  sprintf(assert, "Count: %u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default73) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned int u = -2147483648;
  s21_sprintf(result, "Count: %u abc", u);
  sprintf(assert, "Count: %u abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default75) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned long int u = 2323232323;
  s21_sprintf(result, "Count: %lu abc", u);
  sprintf(assert, "Count: %lu abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default76) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned long int u = 9223372036854775807;
  s21_sprintf(result, "Count: %lu abc", u);
  sprintf(assert, "Count: %lu abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default77) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned short int u = 32767;
  s21_sprintf(result, "Count: %hu abc", u);
  sprintf(assert, "Count: %hu abc", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default78) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned short int u = 32770;
  s21_sprintf(result, "Count: %hu end", u);
  sprintf(assert, "Count: %hu end", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default79) {
  char result[40] = {0};
  char assert[40] = {0};
  unsigned int u = 327710;
  s21_sprintf(result, "Count: %11.10u end", u);
  sprintf(assert, "Count: %11.10u end", u);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default80) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%g";
  double hex = 0.50300;
  ck_assert_int_eq(s21_sprintf(str1, format, hex), sprintf(str2, format, hex));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default81) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%g";
  double hex = 5131.43;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default82) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%g";
  double hex = 0.1;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default83) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%.5g";
  double hex = 0.55555;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default84) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%.0g";
  double hex = 0.4;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
/*START_TEST(test_default85) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%.g";
  double hex = 5;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
*/
END_TEST
START_TEST(test_default86) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%.g";
  double hex = 0.0004;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default87) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%g";
  double hex = 0;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default88) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%.5g";
  double hex = 0;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default89) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%5g";
  double hex = 0.0000005;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default90) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%5.8g";
  double hex = 0.0000005;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default91) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char format[] = "%g";
  double hex = 0.005;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default92) {
  char str1[BUFF_SIZE] = {'\0'};
  char str2[BUFF_SIZE] = {'\0'};
  char format[] = "%LG";
  long double hex = 0.000005;
  s21_sprintf(str1, format, hex);
  sprintf(str2, format, hex);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default93) {
  char str1[BUFF_SIZE] = {'\0'};
  char str2[BUFF_SIZE] = {'\0'};
  char format[] = "%LG %g %G %Lg %.5g";
  long double hex = 0.000005;
  double hex1 = 41.1341;
  double hex2 = 848.9000;
  long double hex3 = 0.0843;
  double hex4 = 0.0005;
  double hex5 = 0.8481481;
  s21_sprintf(str1, format, hex, hex1, hex2, hex3, hex4, hex5);
  sprintf(str2, format, hex, hex1, hex2, hex3, hex4, hex5);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default94) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.15Le";
  long double val = 15.35;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default95) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.0Le";
  long double val = 15.35;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default96) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.Le";
  long double val = 15.000009121;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default97) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.15Le";
  long double val = 0.000000000000000123;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default98) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%.15Le";
  long double val = -15.35581134;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default99) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "%Le";
  long double val = 72537572375.1431341;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default102) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  char *format = "% .0e %.le %Le %e %le %Le";
  float val = 0;
  double val1 = 0;
  long double val2 = 3515315.153151;
  float val3 = 5.5;
  double val4 = 0.094913941;
  long double val5 = 95919539159.53151351131;
  s21_sprintf(str1, format, val, val1, val2, val3, val4, val5);
  sprintf(str2, format, val, val1, val2, val3, val4, val5);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default103) {
  char str1[BUFF_SIZE] = {'\0'};
  char str2[BUFF_SIZE] = {'\0'};
  char *format = "%.15LE";
  long double val = 4134121;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default104) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  ck_assert_int_eq(s21_sprintf(str1, "abc"), sprintf(str2, "abc"));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default105) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  ck_assert_int_eq(s21_sprintf(str1, "abc"), sprintf(str2, "abc"));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default106) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%15o";
  int val = 14140;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default107) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%-16o";
  int val = 14140;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default108) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%.51o";
  int val = 14140;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default109) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%-5.51o";
  int val = 14140;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default110) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%o";
  ck_assert_int_eq(s21_sprintf(str1, format, 0), sprintf(str2, format, 0));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default111) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#o";
  int val = 57175;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default112) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%hd";
  short int val = 14140;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default113) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%lo";
  long int val = 949149114140;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

// START_TEST(test_default114) {
//   char str1[BUFF_SIZE] = {0};
//   char str2[BUFF_SIZE] = {0};

//   char *format = "%lo, %o, %ho, %.5o, %5.o";
//   long int val = 949149114140;
//   ck_assert_int_eq(
//       s21_sprintf(str1, format, val, 14, 1441, 14414, 9681),
//       sprintf(str2, format, val, (unsigned)14, (unsigned short)1441,
//               (unsigned)14414, (unsigned)9681));

//   ck_assert_str_eq(str1, str2);
// }
// END_TEST

START_TEST(test_default115) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%lo";
  long int val = 84518;
  ck_assert_int_eq(s21_sprintf(str1, format, val), sprintf(str2, format, val));

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default116) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#o";
  int val = -57175;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default117) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#- 10o";
  int val = -573375;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default118) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%5x";
  unsigned val = 858158158;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default119) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#-10x";
  unsigned val = 858158158;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default120) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%.15x";
  unsigned val = 858158158;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default121) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#-10x %x %X %#x %#X %5.5x";
  unsigned val = 858158158;
  s21_sprintf(str1, format, val, val, val, val, val, val);
  sprintf(str2, format, val, val, val, val, val, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default122) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#-5.10x";
  unsigned val = 858158158;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default123) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#x";
  unsigned val = 0;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default124) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#x";
  unsigned val = 18571;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default125) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#hx";
  unsigned short val = 12352;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default126) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#lx";
  unsigned long val = 18571757371571;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default127) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#2x";
  unsigned val = 1;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default128) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%#30x";
  unsigned val = 1;
  s21_sprintf(str1, format, val);
  sprintf(str2, format, val);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default129) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%p";
  s21_sprintf(str1, format, format);
  sprintf(str2, format, format);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default130) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%15p";
  s21_sprintf(str1, format, format);
  sprintf(str2, format, format);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default131) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%.5p";
  s21_sprintf(str1, format, format);
  sprintf(str2, format, format);

  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(test_default132) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};

  char *format = "%p";
  char *ptr = "(nil)";
  s21_sprintf(str1, format, ptr);
  sprintf(str2, format, ptr);

  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default133) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  int ret = 0;
  char *format = "How many chars written before n %n";
  s21_sprintf(str1, format, &ret);
  sprintf(str2, format, &ret);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default134) {
  char str1[BUFF_SIZE] = {0};
  char str2[BUFF_SIZE] = {0};
  int n1;
  int n2;
  s21_sprintf(str1, "%d%n", 123, &n1);
  sprintf(str2, "%d%n", 123, &n2);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(test_default135) {
  char result[512] = {0};
  char assert[512] = {0};
  char *d = "2147";
  s21_sprintf(result, "%101s", d);
  sprintf(assert, "%101s", d);
  ck_assert_str_eq(result, assert);
}
END_TEST

START_TEST(test_default136) {
  char result[512] = {0};
  char assert[512] = {0};
  char c = 'z';
  s21_sprintf(result, "Count: %12lc", c);
  sprintf(assert, "Count: %12lc", c);
  ck_assert_str_eq(result, assert);
}
END_TEST

// START_TEST(test_s21_sscanf_spec_c) {
//   char format_str[] = "%c %c%c  %c";
//   char str[] = "1 a 3   c          ";
//   char a1, a2, a3, a4, b1, b2, b3, b4;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &a4);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &b4);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(a1, b1);
//   ck_assert_int_eq(a2, b2);
//   ck_assert_int_eq(a3, b3);
//   ck_assert_int_eq(a4, b4);
// }
// END_TEST

// START_TEST(test_s21_sscanf_spec_c2) {
//   char format_str[] = "%*c%c %c %c  %c";
//   char str[] = "7   1 a 3\n t";
//   char a1, a2, a3, a4, b1, b2, b3, b4;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &a4);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &b4);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(a1, b1);
//   ck_assert_int_eq(a2, b2);
//   ck_assert_int_eq(a3, b3);
//   ck_assert_int_eq(a4, b4);
// }
// END_TEST

START_TEST(test_s21_sscanf_spec_d) {
  char format_str[] = "%d %d %d";
  char str[] = "456 -8 087";
  int a1, a2, a3, b1, b2, b3;

  int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3);
  int num_match2 = sscanf(str, format_str, &b1, &b2, &b3);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_int_eq(a1, b1);
  ck_assert_int_eq(a2, b2);
  ck_assert_int_eq(a3, b3);
}
END_TEST

START_TEST(test_s21_sscanf_spec_d2) {
  char format_str[] = "%*d %2d %d %d";
  char str[] = "67 456 -8 087";
  int a1, a2, a3, b1, b2, b3;

  int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3);
  int num_match2 = sscanf(str, format_str, &b1, &b2, &b3);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_int_eq(a1, b1);
  ck_assert_int_eq(a2, b2);
  ck_assert_int_eq(a3, b3);
}
END_TEST

// START_TEST(test_s21_sscanf_spec_i) {
//   char format_str[] = "Number: %i, Hex: %i, Octal number: %i";
//   char str[] = "Number: 123, Hex: -0xFF, Octal number: 0145";
//   int a1, a2, a3, b1, b2, b3 = 0;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(a1, b1);
//   ck_assert_int_eq(a2, b2);
//   ck_assert_int_eq(a3, b3);
// }
// END_TEST

// START_TEST(test_s21_sscanf_spec_i2) {
//   char format_str[] = "Number: %i, Hex: %i, Octal number: %i";
//   char str[] = "Number: -0123, Hex: +0xFFf, Octal number: -0145";
//   int a1, a2, a3, b1, b2, b3 = 0;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(a1, b1);
//   ck_assert_int_eq(a2, b2);
//   ck_assert_int_eq(a3, b3);
// }
// END_TEST

// START_TEST(test_s21_sscanf_spec_i_and_n) {
//   char format_str[] = "%*d Number: %i, Hex: %i, Octal number: %i %n";
//   char str[] = "45 Number: 123, Hex: -0xFF, Octal number: 0145";
//   int a1, a2, a3, b1, b2, b3, n, n2 = 0;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &n);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(a1, b1);
//   ck_assert_int_eq(a2, b2);
//   ck_assert_int_eq(a3, b3);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

START_TEST(test_s21_sscanf_spec_egf) {
  char format_str[] = "%e %E %g %G %f";
  char str[] = "1.048576E+6 1.0986e+0 5e0 1.23e-4 5.77";
  float a1, a2, a3, a4, a5, b1, b2, b3, b4, b5;

  int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &a4, &a5);
  int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &b4, &b5);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_float_eq(a1, b1);
  ck_assert_float_eq(a2, b2);
  ck_assert_float_eq(a3, b3);
  ck_assert_float_eq(a4, b4);
  ck_assert_float_eq(a5, b5);
}
END_TEST

START_TEST(test_s21_sscanf_spec_egf2) {
  char format_str[] = "%*f %e %E %g %G %f";
  char str[] = "76.8 -1.048576E+6 +1.0986e+0 5e0 01.23e-4 -5.77";
  float a1, a2, a3, a4, a5, b1, b2, b3, b4, b5;

  int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &a4, &a5);
  int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &b4, &b5);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_float_eq(a1, b1);
  ck_assert_float_eq(a2, b2);
  ck_assert_float_eq(a3, b3);
  ck_assert_float_eq(a4, b4);
  ck_assert_float_eq(a5, b5);
}
END_TEST

START_TEST(test_s21_sscanf_spec_oux) {
  char format[] = "%o%o %u %X %x";
  char str[] = "1237 2 9865 0x1A3F 0xD";
  unsigned int a1, a2, a3, a4, a5, b1, b2, b3, b4, b5;

  int num_match = s21_sscanf(str, format, &a1, &a2, &a3, &a4, &a5);
  int num_match2 = sscanf(str, format, &b1, &b2, &b3, &b4, &b5);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_uint_eq(a1, b1);
  ck_assert_uint_eq(a2, b2);
  ck_assert_uint_eq(a3, b3);
  ck_assert_uint_eq(a4, b4);
  ck_assert_uint_eq(a5, b5);
}
END_TEST

START_TEST(test_s21_sscanf_spec_oux2) {
  char format[] = "%*o %2o%2o %u %X %x";
  char str[] = "45 1237 2 9865 0x1A3F 0xD";
  unsigned int a1, a2, a3, a4, a5, b1, b2, b3, b4, b5;

  int num_match = s21_sscanf(str, format, &a1, &a2, &a3, &a4, &a5);
  int num_match2 = sscanf(str, format, &b1, &b2, &b3, &b4, &b5);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_uint_eq(a1, b1);
  ck_assert_uint_eq(a2, b2);
  ck_assert_uint_eq(a3, b3);
  ck_assert_uint_eq(a4, b4);
  ck_assert_uint_eq(a5, b5);
}
END_TEST

START_TEST(test_s21_sscanf_spec_str) {
  const char str[] = "Aboba Floppa Keppa Shleppa Anuroba";
  const char format[] = "%s %s %s %s";

  char s1[BUFF_SIZE] = {'\0'};
  char s2[BUFF_SIZE] = {'\0'};
  char s3[BUFF_SIZE] = {'\0'};
  char s4[BUFF_SIZE] = {'\0'};

  char s5[BUFF_SIZE] = {'\0'};
  char s6[BUFF_SIZE] = {'\0'};
  char s7[BUFF_SIZE] = {'\0'};
  char s8[BUFF_SIZE] = {'\0'};

  int num_match = s21_sscanf(str, format, s1, s2, s3, s4);
  int num_match2 = sscanf(str, format, s5, s6, s7, s8);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_str_eq(s1, s5);
  ck_assert_str_eq(s2, s6);
  ck_assert_str_eq(s3, s7);
  ck_assert_str_eq(s4, s8);
}
END_TEST

START_TEST(test_s21_sscanf_spec_str2) {
  const char str[] = "Aboba hhh Floppa Keppa ";
  const char format[] = "%3s %*s %4s %n %6s %7s%n";

  char s1[BUFF_SIZE] = {'\0'};
  char s2[BUFF_SIZE] = {'\0'};
  char s3[BUFF_SIZE] = {'\0'};
  char s4[BUFF_SIZE] = {'\0'};

  char s5[BUFF_SIZE] = {'\0'};
  char s6[BUFF_SIZE] = {'\0'};
  char s7[BUFF_SIZE] = {'\0'};
  char s8[BUFF_SIZE] = {'\0'};

  int n, n2, n4, n3 = 0;

  int num_match = s21_sscanf(str, format, s1, s2, &n, s3, s4, &n3);
  int num_match2 = sscanf(str, format, s5, s6, &n2, s7, s8, &n4);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_str_eq(s1, s5);
  ck_assert_str_eq(s2, s6);
  ck_assert_str_eq(s3, s7);
  ck_assert_str_eq(s4, s8);
  ck_assert_int_eq(n, n2);
  ck_assert_int_eq(n3, n4);
}
END_TEST

START_TEST(test_s21_sscanf_spec_ptr_and_n) {
  const char str[] = "0xFFFF 0xBBC1FF 7fffbf5ad18c";
  const char format[] = "%p %p %p%n";
  void *a1, *a2, *a3, *b1, *b2, *b3;
  int a4, b4;

  int num_match = s21_sscanf(str, format, &a1, &a2, &a3, &a4);
  int num_match2 = sscanf(str, format, &b1, &b2, &b3, &b4);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_ptr_eq(a1, b1);
  ck_assert_ptr_eq(a2, b2);
  ck_assert_ptr_eq(a3, b3);
  ck_assert_int_eq(a4, b4);
}
END_TEST

START_TEST(test_s21_sscanf_perсent) {
  const char str[] = "100%5 completed";
  const char format[] = "%d%%%d completed";
  int a1, a2, b1, b2;

  int num_match = s21_sscanf(str, format, &a1, &a2);
  int num_match2 = sscanf(str, format, &b1, &b2);

  ck_assert_int_eq(num_match, num_match2);
  ck_assert_int_eq(a1, b1);
  ck_assert_int_eq(a2, b2);
}
END_TEST

// START_TEST(test_s21_sscanf_many_args) {
//   const char str[] = "-76 123456 1234567 0x89ABCDEF 0x12345678 -0xFF - 1.048576E-6 1.048576E+6 " " ThisIsAString C 0x7fffd602dfb4 3.14 ";
//   const char format[] = "%d %u %o %x %X %i %e %g %s %c %p %f%n";
//   unsigned int u, u2, o, o2, x, x2, X, X2;
//   int i, i2, d, d2;
//   float f, f2, e, e2, g, g2;
//   char s[100], s2[100], c, c2;
//   void *p, *p2;
//   int n, n2;

//   int num_match = s21_sscanf(str, format, &d, &u, &o, &x, &X, &i, &e, &g, s, &c,
//                              &p, &f, &n);
//   int num_match2 = sscanf(str, format, &d2, &u2, &o2, &x2, &X2, &i2, &e2, &g2,
//                           s2, &c2, &p2, &f2, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_uint_eq(u, u2);
//   ck_assert_uint_eq(o, o2);
//   ck_assert_uint_eq(x, x2);
//   ck_assert_uint_eq(X, X2);
//   ck_assert_int_eq(i, i2);
//   ck_assert_float_eq(e, e2);
//   ck_assert_float_eq(g, g2);
//   ck_assert_str_eq(s, s2);
//   ck_assert_int_eq(c, c2);
//   ck_assert_ptr_eq(p, p2);
//   ck_assert_float_eq(f, f2);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_mod_h) {
//   const char str[] = "-76 -0xD 5 128 0xC 0xD";
//   const char format[] = "%hd %hi %ho %hu %hx %hX";
//   short u, u2, o, o2, x, x2, X, X2, i, i2, d, d2;

//   int num_match = s21_sscanf(str, format, &d, &i, &o, &u, &x, &X);
//   int num_match2 = sscanf(str, format, &d2, &i2, &o2, &u2, &x2, &X2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_int_eq(u, u2);
//   ck_assert_int_eq(o, o2);
//   ck_assert_int_eq(x, x2);
//   ck_assert_int_eq(X, X2);
//   ck_assert_int_eq(i, i2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_mod_l) {
//   const char str[] = "-76985432 -0xDDDDDD 5543217 128000000 0x3D3F 2878D9F2";
//   const char format[] = "%ld %li %lo %lu %lx %lX";
//   long u, u2, o, o2, x, x2, X, X2, i, i2, d, d2;

//   int num_match = s21_sscanf(str, format, &d, &i, &o, &u, &x, &X);
//   int num_match2 = sscanf(str, format, &d2, &i2, &o2, &u2, &x2, &X2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_int_eq(u, u2);
//   ck_assert_int_eq(o, o2);
//   ck_assert_int_eq(x, x2);
//   ck_assert_int_eq(X, X2);
//   ck_assert_int_eq(i, i2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_mod_L) {
//   const char str[] =
//       "-769855.43206532 1.048576E+6 5543.0000217 5.5e-4 9888.65422";
//   const char format[] = "%Le %LE %Lf %Lg %LG";
//   long double e, e2, E, E2, f, f2, g, g2, G, G2;

//   int num_match = s21_sscanf(str, format, &e, &E, &f, &g, &G);
//   int num_match2 = sscanf(str, format, &e2, &E2, &f2, &g2, &G2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_double_eq(e, e2);
//   ck_assert_double_eq(E, E2);
//   ck_assert_double_eq(f, f2);
//   ck_assert_double_eq(g, g2);
//   ck_assert_double_eq(G, G2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_mod_ignore) {
//   const char str[] ="-76 123456 1234567 0x89ABCDEF 0x12345678 -0xFF - 1.048576E-6 1.048576E+6 " " ThisIsAString C 0x7fffd602dfb4 3.14 ";
//   const char format[] = "%*d %*u %*o %*x %*X %*i %*e %*g %*s %*c %*p %*f%n";
//   int n, n2;

//   int num_match = s21_sscanf(str, format, &n);
//   int num_match2 = sscanf(str, format, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_mod_width) {
//   const char str[] =
//       "-76 123456 1234567 0x89ABCDE890  1.048576E-60x12345678 -0xFF "
//       "1.048576E-6 ThisIsAString C 0x7fffd602dfb4 3.14";
//   const char format[] =
//       "%4d %3u %6o %7x %9X %5i %5e %11g %13s %c %14p
//       % 4f %
//       n "; unsigned int u, u2, o, o2, x, x2, X, X2; int i, i2, d, d2; float f,
//       f2,
//              e, e2, g, g2;
//   char s[100], s2[100], c, c2;
//   void *p, *p2;
//   int n, n2;

//   int num_match = s21_sscanf(str, format, &d, &u, &o, &x, &X, &i, &e, &g, s, &c,
//                              &p, &f, &n);
//   int num_match2 = sscanf(str, format, &d2, &u2, &o2, &x2, &X2, &i2, &e2, &g2,
//                           s2, &c2, &p2, &f2, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_uint_eq(u, u2);
//   ck_assert_uint_eq(o, o2);
//   ck_assert_uint_eq(x, x2);
//   ck_assert_uint_eq(X, X2);
//   ck_assert_int_eq(i, i2);
//   ck_assert_float_eq(e, e2);
//   ck_assert_float_eq(g, g2);
//   ck_assert_str_eq(s, s2);
//   ck_assert_int_eq(c, c2);
//   ck_assert_ptr_eq(p, p2);
//   ck_assert_float_eq(f, f2);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal1) {
//   char format_str[] = "%c %c%c  %c";
//   char str[] = "1t5 7";
//   char a1, a2, a3, a4, b1, b2, b3, b4 = 0;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &a4);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &b4);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(a1, b1);
//   ck_assert_int_eq(a2, b2);
//   ck_assert_int_eq(a3, b3);
//   ck_assert_int_eq(a4, b4);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal2) {
//   char format_str[] = "%3c%7c%n%c%9c";
//   char str[] = "Among\t the\n blind the one-eyed man is king.";
//   char a1[3], a2[7], a3, a4[9], b1[3], b2[7], b3, b4[9];
//   int n, n2;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &n, &a3, &a4);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &n2, &b3, &b4);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(*a1, *b1);
//   ck_assert_int_eq(*a2, *b2);
//   ck_assert_int_eq(n, n2);
//   ck_assert_int_eq(a3, b3);
//   ck_assert_int_eq(*a4, *b4);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal3) {
//   const char str[] = "-76 -0xD 065 128 ";
//   const char format[] = "%5hd %4hi %3ho %hu %hx %hX%n";
//   short u, u2, o, o2, x, x2, X, X2, i, i2, d, d2;
//   int n, n2 = 0;

//   int num_match = s21_sscanf(str, format, &d, &i, &o, &u, &x, &X, &n);
//   int num_match2 = sscanf(str, format, &d2, &i2, &o2, &u2, &x2, &X2, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_int_eq(u, u2);
//   ck_assert_int_eq(o, o2);
//   ck_assert_int_eq(i, i2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal4) {
//   const char str[] = "76 -0xD 5 128 0xC 0xD";
//   const char format[] = "%*d %4li %*o %4u%n %*x %lX";
//   int n, n2, u, u2 = 0;
//   long i, i2, X, X2;

//   int num_match = s21_sscanf(str, format, &i, &u, &n, &X);
//   int num_match2 = sscanf(str, format, &i2, &u2, &n2, &X2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(i, i2);
//   ck_assert_int_eq(u, u2);
//   ck_assert_int_eq(n, n2);
//   ck_assert_int_eq(X, X2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal5) {
//   char format_str[] = "%e %E %g %G %f%n";
//   char str[] = "1.048576E+6    1.0986e+0   ,  6.8";
//   float a1, a2, a3, a4, a5, b1, b2, b3, b4, b5;
//   int n, n2;

//   int num_match = s21_sscanf(str, format_str, &a1, &a2, &a3, &a4, &a5, &n);
//   int num_match2 = sscanf(str, format_str, &b1, &b2, &b3, &b4, &b5, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_float_eq(a1, b1);
//   ck_assert_float_eq(a2, b2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal6) {
//   const char str[] =
//       "-769855.43206532 1.048576E+6 5543.0000217 5.5e-4 9888.65422";
//   const char format[] = "%*e %LE %*f  %n %6g %LG";
//   long double E, E2, G, G2;
//   float g, g2;
//   int n, n2;

//   int num_match = s21_sscanf(str, format, &E, &n, &g, &G);
//   int num_match2 = sscanf(str, format, &E2, &n2, &g2, &G2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_double_eq(E, E2);
//   ck_assert_int_eq(n, n2);
//   ck_assert_float_eq(g, g2);
//   ck_assert_double_eq(G, G2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal7) {
//   const char str[] =
//       "-769855.43206532\n     1.048576E+6\t 5543.0000217\n\n\n 5.5e-4 "
//       "9888.65422";
//   const char format[] = "%*e %LE %*f  %n %6g %LG%n";
//   long double E, E2, G, G2;
//   float g, g2;
//   int n, n2, n3, n4;

//   int num_match = s21_sscanf(str, format, &E, &n, &g, &G, &n3);
//   int num_match2 = sscanf(str, format, &E2, &n2, &g2, &G2, &n4);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_double_eq(E, E2);
//   ck_assert_int_eq(n, n2);
//   ck_assert_float_eq(g, g2);
//   ck_assert_double_eq(G, G2);
//   ck_assert_int_eq(n3, n4);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal8) {
//   const char str[] = "Abob/\n Kep.pa\t Shl0eppa   ggg   ";
//   const char format[] = "%s %s %s %s %n";

//   char s1[BUFF_SIZE] = {'\0'};
//   char s2[BUFF_SIZE] = {'\0'};
//   char s3[BUFF_SIZE] = {'\0'};
//   char s4[BUFF_SIZE] = {'\0'};

//   char s5[BUFF_SIZE] = {'\0'};
//   char s6[BUFF_SIZE] = {'\0'};
//   char s7[BUFF_SIZE] = {'\0'};
//   char s8[BUFF_SIZE] = {'\0'};

//   int n, n2 = 0;

//   int num_match = s21_sscanf(str, format, s1, s2, s3, s4, &n);
//   int num_match2 = sscanf(str, format, s5, s6, s7, s8, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_str_eq(s1, s5);
//   ck_assert_str_eq(s2, s6);
//   ck_assert_str_eq(s3, s7);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal9) {
//   const char str[] = "-76 -0xD 5 128 0xC\t\t  9877\n\t ";
//   const char format[] = "%hd %hi %ho %hu %hx %hX%n";
//   short u, u2, o, o2, x, x2, X, X2;
//   short i, i2, d, d2;
//   int n, n2;

//   int num_match = s21_sscanf(str, format, &d, &i, &o, &u, &x, &X, &n);
//   int num_match2 = sscanf(str, format, &d2, &i2, &o2, &u2, &x2, &X2, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_int_eq(i, i2);
//   ck_assert_int_eq(o, o2);
//   ck_assert_int_eq(u, u2);
//   ck_assert_int_eq(x, x2);
//   ck_assert_int_eq(X, X2);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal10) {
//   const char str[] = "0xFFFF\n\n 0xBBC1FF\t 7fffbf5ad18c";
//   const char format[] = "%p %p %p%n";
//   void *a1, *a2, *a3, *b1, *b2, *b3;
//   int a4, b4;

//   int num_match = s21_sscanf(str, format, &a1, &a2, &a3, &a4);
//   int num_match2 = sscanf(str, format, &b1, &b2, &b3, &b4);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_ptr_eq(a1, b1);
//   ck_assert_ptr_eq(a2, b2);
//   ck_assert_ptr_eq(a3, b3);
//   ck_assert_int_eq(a4, b4);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal11) {
//   const char str[] = "0xff -76g -0xff 67890    879.76543\n ";
//   const char format[] = "%*x %5s %li %*d %Lf%n %p%n";
//   char s1[BUFF_SIZE] = {'\0'};
//   char s2[BUFF_SIZE] = {'\0'};
//   long i, i2;
//   long double f, f2;
//   void *p, *p2;
//   int n, n2, n3, n4;
//   int num_match = s21_sscanf(str, format, s1, &i, &f, &n, &p, &n3);
//   int num_match2 = sscanf(str, format, s2, &i2, &f2, &n2, &p2, &n4);
//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_str_eq(s1, s2);
//   ck_assert_int_eq(i, i2);
//   ck_assert_double_eq(f, f2);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

// START_TEST(test_s21_sscanf_abnormal12) {
//   const char str[] =
//       "+76 +123456 1234567 0x89ABCDE+890  1.048576E-60x12345678 +0xFF "
//       "1.048576E-6 +ThisIsAString C 0x7fffd602dfb4 +3.14";
//   const char format[] =
//       "%4d %3u %6o %7x %9X %5i %5e %11g %13s %c %14p
//       % 4f %
//       n "; unsigned int u, u2, o, o2, x, x2, X, X2; int i, i2, d, d2; float f,
//       f2,
//              e, e2, g, g2;
//   char s[100], s2[100], c, c2;
//   void *p, *p2;
//   int n, n2;

//   int num_match = s21_sscanf(str, format, &d, &u, &o, &x, &X, &i, &e, &g, s, &c,
//                              &p, &f, &n);
//   int num_match2 = sscanf(str, format, &d2, &u2, &o2, &x2, &X2, &i2, &e2, &g2,
//                           s2, &c2, &p2, &f2, &n2);

//   ck_assert_int_eq(num_match, num_match2);
//   ck_assert_int_eq(d, d2);
//   ck_assert_uint_eq(u, u2);
//   ck_assert_uint_eq(o, o2);
//   ck_assert_uint_eq(x, x2);
//   ck_assert_uint_eq(X, X2);
//   ck_assert_int_eq(i, i2);
//   ck_assert_float_eq(e, e2);
//   ck_assert_float_eq(g, g2);
//   ck_assert_str_eq(s, s2);
//   ck_assert_int_eq(c, c2);
//   ck_assert_ptr_eq(p, p2);
//   ck_assert_float_eq(f, f2);
//   ck_assert_int_eq(n, n2);
// }
// END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
  srunner_set_fork_status(sr, CK_NOFORK);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, strlen_test);
  tcase_add_test(tc1_1, strcspn_test);
  tcase_add_test(tc1_1, strerror_test);
  tcase_add_test(tc1_1, strtok_test);
  tcase_add_test(tc1_1, strncpy_test);
  tcase_add_test(tc1_1, memcpy_test);
  tcase_add_test(tc1_1, memset_test);
  tcase_add_test(tc1_1, strstr_test);
  tcase_add_test(tc1_1, strchr_test);
  tcase_add_test(tc1_1, strrchr_test);
  tcase_add_test(tc1_1, memchr_test);
  tcase_add_test(tc1_1, strpbrk_test);
  tcase_add_test(tc1_1, memcmp_test);
  tcase_add_test(tc1_1, strncmp_test);
  tcase_add_test(tc1_1, test_default);
  tcase_add_test(tc1_1, test_default2);
  tcase_add_test(tc1_1, test_default3);
  tcase_add_test(tc1_1, test_default4);
  tcase_add_test(tc1_1, test_default5);
  tcase_add_test(tc1_1, test_default6);
  tcase_add_test(tc1_1, test_default7);
  tcase_add_test(tc1_1, test_default9);
  tcase_add_test(tc1_1, test_default10);
  tcase_add_test(tc1_1, test_default11);
  tcase_add_test(tc1_1, test_default12);
  tcase_add_test(tc1_1, test_default13);
  tcase_add_test(tc1_1, test_default14);
  tcase_add_test(tc1_1, test_default15);
  tcase_add_test(tc1_1, test_default16);
  tcase_add_test(tc1_1, test_default17);
  tcase_add_test(tc1_1, test_default18);
  tcase_add_test(tc1_1, test_default19);
  tcase_add_test(tc1_1, test_default20);
  tcase_add_test(tc1_1, test_default21);
  tcase_add_test(tc1_1, test_default22);
  tcase_add_test(tc1_1, test_default23);
  tcase_add_test(tc1_1, test_default24);
  tcase_add_test(tc1_1, test_default25);
  tcase_add_test(tc1_1, test_default26);
  tcase_add_test(tc1_1, test_default27);
  tcase_add_test(tc1_1, test_default28);
  tcase_add_test(tc1_1, test_default29);
  tcase_add_test(tc1_1, test_default30);
  tcase_add_test(tc1_1, test_default31);
  tcase_add_test(tc1_1, test_default32);
  tcase_add_test(tc1_1, test_default33);
  tcase_add_test(tc1_1, test_default34);
  tcase_add_test(tc1_1, test_default35);
  tcase_add_test(tc1_1, test_default36);
  tcase_add_test(tc1_1, test_default37);
  tcase_add_test(tc1_1, test_default38);
  tcase_add_test(tc1_1, test_default39);
  tcase_add_test(tc1_1, test_default40);
  tcase_add_test(tc1_1, test_default43);
  tcase_add_test(tc1_1, test_default44);
  tcase_add_test(tc1_1, test_default45);
  tcase_add_test(tc1_1, test_default46);
  tcase_add_test(tc1_1, test_default47);
  tcase_add_test(tc1_1, test_default48);
  tcase_add_test(tc1_1, test_default49);
  tcase_add_test(tc1_1, test_default50);
  tcase_add_test(tc1_1, test_default51);
  tcase_add_test(tc1_1, test_default52);
  tcase_add_test(tc1_1, test_default53);
  tcase_add_test(tc1_1, test_default54);
  tcase_add_test(tc1_1, test_default55);
  tcase_add_test(tc1_1, test_default56);
  tcase_add_test(tc1_1, test_default57);
  tcase_add_test(tc1_1, test_default58);
  tcase_add_test(tc1_1, test_default59);
  tcase_add_test(tc1_1, test_default60);
  tcase_add_test(tc1_1, test_default61);
  tcase_add_test(tc1_1, test_default62);
  tcase_add_test(tc1_1, test_default63);
  tcase_add_test(tc1_1, test_default65);
  tcase_add_test(tc1_1, test_default66);
  tcase_add_test(tc1_1, test_default67);
  tcase_add_test(tc1_1, test_default68);
  tcase_add_test(tc1_1, test_default69);
  tcase_add_test(tc1_1, test_default70);
  tcase_add_test(tc1_1, test_default71);
  tcase_add_test(tc1_1, test_default72);
  tcase_add_test(tc1_1, test_default73);
  tcase_add_test(tc1_1, test_default75);
  tcase_add_test(tc1_1, test_default76);
  tcase_add_test(tc1_1, test_default77);
  tcase_add_test(tc1_1, test_default78);
  tcase_add_test(tc1_1, test_default79);
  tcase_add_test(tc1_1, test_default80);
  tcase_add_test(tc1_1, test_default81);
  tcase_add_test(tc1_1, test_default82);
  tcase_add_test(tc1_1, test_default83);
  tcase_add_test(tc1_1, test_default84);
  tcase_add_test(tc1_1, test_default86);
  tcase_add_test(tc1_1, test_default87);
  tcase_add_test(tc1_1, test_default88);
  tcase_add_test(tc1_1, test_default89);
  tcase_add_test(tc1_1, test_default90);
  tcase_add_test(tc1_1, test_default91);
  tcase_add_test(tc1_1, test_default92);
  tcase_add_test(tc1_1, test_default93);
  tcase_add_test(tc1_1, test_default94);
  tcase_add_test(tc1_1, test_default95);
  tcase_add_test(tc1_1, test_default96);
  tcase_add_test(tc1_1, test_default97);
  tcase_add_test(tc1_1, test_default98);
  tcase_add_test(tc1_1, test_default99);
  tcase_add_test(tc1_1, test_default102);
  tcase_add_test(tc1_1, test_default103);
  tcase_add_test(tc1_1, test_default104);
  tcase_add_test(tc1_1, test_default105);
  tcase_add_test(tc1_1, test_default106);
  tcase_add_test(tc1_1, test_default107);
  tcase_add_test(tc1_1, test_default108);
  tcase_add_test(tc1_1, test_default109);
  tcase_add_test(tc1_1, test_default110);
  tcase_add_test(tc1_1, test_default111);
  tcase_add_test(tc1_1, test_default112);
  tcase_add_test(tc1_1, test_default113);
  tcase_add_test(tc1_1, test_default115);
  tcase_add_test(tc1_1, test_default116);
  tcase_add_test(tc1_1, test_default117);
  tcase_add_test(tc1_1, test_default118);
  tcase_add_test(tc1_1, test_default119);
  tcase_add_test(tc1_1, test_default120);
  tcase_add_test(tc1_1, test_default121);
  tcase_add_test(tc1_1, test_default122);
  tcase_add_test(tc1_1, test_default123);
  tcase_add_test(tc1_1, test_default124);
  tcase_add_test(tc1_1, test_default125);
  tcase_add_test(tc1_1, test_default126);
  tcase_add_test(tc1_1, test_default127);
  tcase_add_test(tc1_1, test_default128);
  tcase_add_test(tc1_1, test_default129);
  tcase_add_test(tc1_1, test_default130);
  tcase_add_test(tc1_1, test_default131);
  tcase_add_test(tc1_1, test_default132);
  tcase_add_test(tc1_1, test_default133);
  tcase_add_test(tc1_1, test_default134);
  tcase_add_test(tc1_1, test_default135);
  tcase_add_test(tc1_1, test_default136);
  tcase_add_test(tc1_1, test_many_string);
  tcase_add_test(tc1_1, float_precision);
  tcase_add_test(tc1_1, float_width);
  tcase_add_test(tc1_1, float_precision_zero);
  tcase_add_test(tc1_1, float_precision_empty);
  tcase_add_test(tc1_1, float_precision_huge);
  tcase_add_test(tc1_1, float_precision_huge_negative);
  tcase_add_test(tc1_1, float_huge);
  tcase_add_test(tc1_1, float_flags);
  tcase_add_test(tc1_1, test_one_float);
  tcase_add_test(tc1_1, test_many_float);
  tcase_add_test(tc1_1, test_default_multy);
  tcase_add_test(tc1_1, string);
  tcase_add_test(tc1_1, string_precision);
  tcase_add_test(tc1_1, string_width);
  tcase_add_test(tc1_1, string_flags);
  tcase_add_test(tc1_1, string_long);
  tcase_add_test(tc1_1, string_many);
  tcase_add_test(tc1_1, string_width_huge);
  tcase_add_test(tc1_1, test_one_string);
  tcase_add_test(tc1_1, test_many_string);
  tcase_add_test(tc1_1, float_many);
  // tcase_add_test(tc1_1, test_s21_sscanf_spec_c);
  // tcase_add_test(tc1_1, test_s21_sscanf_spec_c2);
  // tcase_add_test(tc1_1, test_s21_sscanf_spec_i);
  // tcase_add_test(tc1_1, test_s21_sscanf_spec_i2);
  // tcase_add_test(tc1_1, test_s21_sscanf_spec_i_and_n);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_d);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_d2);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_egf);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_egf2);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_oux);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_oux2);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_str);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_str2);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_ptr_and_n);
  tcase_add_test(tc1_1, test_s21_sscanf_perсent);
  // tcase_add_test(tc1_1, test_s21_sscanf_many_args);
  // tcase_add_test(tc1_1, test_s21_sscanf_mod_h);
  // tcase_add_test(tc1_1, test_s21_sscanf_mod_l);
  // tcase_add_test(tc1_1, test_s21_sscanf_mod_L);
  // tcase_add_test(tc1_1, test_s21_sscanf_mod_ignore);
  // tcase_add_test(tc1_1, test_s21_sscanf_mod_width);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal1);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal2);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal3);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal4);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal5);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal6);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal7);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal8);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal9);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal10);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal11);
  // tcase_add_test(tc1_1, test_s21_sscanf_abnormal12);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
